# Generated by Django 3.0.5 on 2021-01-28 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 28, 21, 14, 35, 346829), null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 28, 21, 14, 35, 346829), null=True),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 28, 21, 14, 35, 346829), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 28, 21, 14, 35, 351243), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 28, 21, 14, 35, 346829), null=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 28, 21, 14, 35, 346829), null=True),
        ),
    ]
