# Generated by Django 3.0.5 on 2021-02-01 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210128_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 1, 17, 6, 51, 958056), null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 1, 17, 6, 51, 958056), null=True),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 1, 17, 6, 51, 958056), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 1, 17, 6, 51, 964569), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 1, 17, 6, 51, 958056), null=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 1, 17, 6, 51, 958056), null=True),
        ),
    ]
