# Generated by Django 3.0.5 on 2021-02-04 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210201_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 4, 17, 21, 3, 299672), null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 4, 17, 21, 3, 299672), null=True),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 4, 17, 21, 3, 299672), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 4, 17, 21, 3, 305986), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 4, 17, 21, 3, 299672), null=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 4, 17, 21, 3, 299672), null=True),
        ),
    ]
