# Generated by Django 3.0.5 on 2021-02-10 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210204_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 10, 16, 52, 30, 326286), null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 10, 16, 52, 30, 326286), null=True),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 10, 16, 52, 30, 326286), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 10, 16, 52, 30, 336031), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 10, 16, 52, 30, 326286), null=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 10, 16, 52, 30, 326286), null=True),
        ),
    ]
