# Generated by Django 3.0.5 on 2021-02-16 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210210_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 16, 16, 35, 41, 743162), null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 16, 16, 35, 41, 743162), null=True),
        ),
        migrations.AlterField(
            model_name='regadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 16, 16, 35, 41, 743162), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 16, 35, 41, 747562), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 16, 16, 35, 41, 743162), null=True),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='dateadd',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 16, 16, 35, 41, 743162), null=True),
        ),
    ]
