# Generated by Django 3.0.5 on 2021-01-28 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('institut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentnotification',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentnotification',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut.Course'),
        ),
        migrations.AddField(
            model_name='parentnotification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Student'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Course'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Center'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor'),
        ),
        migrations.AddField(
            model_name='holidays',
            name='academicyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Academicyear'),
        ),
        migrations.AddField(
            model_name='handout',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Course'),
        ),
        migrations.AddField(
            model_name='handout',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institut.HandoutSection'),
        ),
        migrations.AddField(
            model_name='grade',
            name='centerlevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Centerlevel'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institut.Classe'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Student'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Course'),
        ),
        migrations.AddField(
            model_name='coursetime',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Course'),
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Course'),
        ),
        migrations.AddField(
            model_name='coursegrades',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor'),
        ),
        migrations.AddField(
            model_name='coursegrades',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Course'),
        ),
        migrations.AddField(
            model_name='coursegrades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.ManyToManyField(to='institut.Coursearea'),
        ),
        migrations.AddField(
            model_name='course',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institut.Classe'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ManyToManyField(to='institut.CourseLanguage'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor'),
        ),
        migrations.AddField(
            model_name='classe',
            name='academicyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Academicyear'),
        ),
        migrations.AddField(
            model_name='classe',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Grade'),
        ),
        migrations.AddField(
            model_name='classe',
            name='student',
            field=models.ManyToManyField(to='profiles.Student'),
        ),
        migrations.AddField(
            model_name='centerlevel',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Center'),
        ),
        migrations.AddField(
            model_name='center',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institut.City'),
        ),
        migrations.AddField(
            model_name='center',
            name='schoolgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institut.Schoolgroup'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='coursetime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut.Coursetime'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('center', 'professor')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('classe', 'student')},
        ),
    ]
