# Generated by Django 3.0.5 on 2021-02-01 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0003_auto_20210128_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentnotification',
            name='readdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentnotification',
            name='notifydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 17, 6, 52, 142639)),
        ),
        migrations.AlterField(
            model_name='parentnotification',
            name='type',
            field=models.CharField(blank=True, choices=[('G', 'Grade'), ('A', 'Attendance'), ('O', 'Course Outline'), ('W', 'Course Work'), ('M', 'Message')], max_length=1, null=True),
        ),
    ]
