# Generated by Django 3.0.5 on 2021-02-04 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210204_1721'),
        ('institut', '0004_auto_20210201_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentnotification',
            name='notifydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 17, 21, 3, 478034)),
        ),
        migrations.RemoveField(
            model_name='parentnotification',
            name='student',
        ),
        migrations.AddField(
            model_name='parentnotification',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Student'),
        ),
    ]
