# Generated by Django 3.0.5 on 2021-02-10 16:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20210210_1652'),
        ('institut', '0005_auto_20210204_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='course',
        ),
        migrations.AddField(
            model_name='notification',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut.Classe'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notifydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 16, 52, 30, 510685)),
        ),
        migrations.AddField(
            model_name='notification',
            name='parentread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='readdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Student'),
        ),
        migrations.AddField(
            model_name='notification',
            name='studentread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='parentnotification',
            name='notifydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 16, 52, 30, 512826)),
        ),
    ]
