# Generated by Django 3.0.5 on 2021-02-16 16:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institut', '0007_auto_20210210_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 16, 35, 41, 842101)),
        ),
        migrations.AlterField(
            model_name='parentnotification',
            name='notifydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 16, 35, 41, 845122)),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('notifydate', models.DateTimeField(default=datetime.datetime(2021, 2, 16, 16, 35, 41, 843560))),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NotificationLog',
                'verbose_name_plural': 'NotificationLogs',
            },
        ),
    ]
